---
# AutoClearLagg (ACL) Settings

# Seconds between each clear lagg
seconds: 300

# Things to clear
items: true
mobs: true

# Messages broadcasted
time-left-message: §cClear lagg in {SECONDS} seconds
items-cleared-message: §cCleared {COUNT} items
mobs-cleared-message: §cCleared {COUNT} mobs

# Countdown times
times: [60, 30, 15, 10, 5, 4, 3, 2, 1]
...
